[navertv_musicbank]
title = "KBS 뮤직뱅크 ─ 네이버TV"
url = "https://tv.naver.com/musicbank/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[navertv_showmusiccore]
title = "MBC 쇼! 음악중심 ─ 네이버TV"
url = "https://tv.naver.com/musiccore/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[navertv_inkigayo]
title = "SBS 인기가요 ─ 네이버TV"
url = "https://tv.naver.com/inkigayo/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[navertv_mcountdown]
title = "Mnet 엠카운트다운 ─ 네이버TV"
url = "https://tv.naver.com/mcountdown/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[navertv_theshow]
title = "SBS MTV 더쇼 ─ 네이버TV"
url = "https://tv.naver.com/theshow/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[navertv_showchampion]
title = "MBC M 쇼챔피언 ─ 네이버TV"
url = "https://tv.naver.com/showchampion/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[navertv_sketchbook]
title = "KBS 유희열의 스케치북 ─ 네이버TV"
url = "https://tv.naver.com/sketchbook/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[navertv_satfreedom]
title = "KBS 불후의 명곡2 전설을 노래하다 ─ 네이버TV"
url = "https://tv.naver.com/satfreedom/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[navertv_mask]
title = "MBC 복면가왕 ─ 네이버TV"
url = "https://tv.naver.com/mask/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[navertv_simplykpop]
title = "ARIRANG 심플리 케이팝 ─ 네이버TV"
url = "https://tv.naver.com/kpop"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[navertv_ubcdran]
title = "UBC 열린예술무대 뒤란 ─ 네이버TV"
url = "https://tv.naver.com/ubcdran/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[navertv_weekidol]
title = "MBC M 주간아이돌 ─ 네이버TV"
url = "https://tv.naver.com/weekidol/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[navertv_amazingsaturday]
title = "tvN 놀라운 토요일 ─ 네이버TV"
url = "https://tv.naver.com/cjenm.amazingsaturday/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[navertv_streetwomanfighter]
title = "Mnet 스트릿 우먼 파이터 ─ 네이버TV"
url = "https://tv.naver.com/cjenm.STREETWOMANFIGHTER/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[navertv_singagain2]
title = "JTBC 싱어게인2 ─ 네이버TV"
url = "https://tv.naver.com/jtbc.singagain2/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"
